apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: exampleuis.example.datalayer.io
spec:
  connectionSecretKeys:
    - kubeconfig
  group: example.datalayer.io
  names:
    kind: ExampleUI
    listKind: ExampleUIList
    singular: exampleui
    plural: exampleuis
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          description: A ExampleUI is a composite resource that represents a K8S Cluster with an example ui installed
          type: object
          properties:
            spec:
              type: object
              properties:
                clusterVersion:
                  type: string
                  description: GKE cluster version
              required:
                - clusterVersion
