apiVersion: database.gcp.crossplane.io/v1beta1
kind: CloudSQLInstance
metadata:
  name: crossplane-example-db-6
spec:
  forProvider:
    databaseVersion: POSTGRES_9_6
    region: us-central1
    settings:
      tier: db-custom-1-3840
      dataDiskType: PD_SSD
      ipConfiguration:
        ipv4Enabled: true
        authorizedNetworks:
          - value: "0.0.0.0/0"
  writeConnectionSecretToRef:
    namespace: crossplane-examples
    name: db-conn-secret
