apiVersion: helm.crossplane.io/v1beta1
kind: Release
metadata:
  name: crossplane-examples
spec:
  providerConfigRef:
    name: helm-provider
  forProvider:
    chart:
      name: crossplane-examples
      repository: http://charts.datalayer.io/charts
      version: 0.0.1
    namespace: crossplane-examples
    values:
      image: datalayer/crossplane-examples:0.0.1
      secret:
        create: true
    env:
      secret:
        endpoint: localhost
        username: datalayer
        password: datalayer
